### ISSUE TITLE
Should "iterator.next()" be debounced in toReadable

### ISSUE THREAD

**Issue by guybedford** [mcollina/stream-iterators-utils#1]
Was just looking the log of this and noticed that the `write(null)` end of iteration case was being called multiple times (8) because `_read` was being called multiple times.

Should we be debouncing this with something like:

```js
function toReadable (iterator, opts) {
  const readable = new Readable(opts);
  readable._read = function () {
    next().catch(onError);
  };
  function onError (err) {
    readable.destroy(err);
  }
  let curNext;
  async function next () {
    if (curNext) return curNext;
    curNext = iterator.next();
    const { value, done } = await curNext;
    curNext = null;
    if (done) {
      readable.push(null);
      return;
    }
    if (readable.push(value)) {
      await next();
    }
  }
  return readable;
}
```

to avoid calling ahead?

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by guybedford** [comment]
Sure, I can do, but am a complete novice with streams so wanted to check if this seems correct first?

**Comment by mcollina** [comment]
I would need to see a repro to be 100% sure, but you have hit a nice bug.

I think the if (readable.push(.. part could be completely omitted to sort the same effect. the stream machinery will fill in the buffer.

**Comment by guybedford** [comment]
I just put together a test on this with the following:

```js
test('toReadable multiple _read calls', ({ plan, is }) => {
  plan(3)

  async function * generate () {
    yield 'a'
    yield 'b'
    yield 'c'
  }

  const stream = toReadable(generate(), { objectMode: true })
  stream._read()
  stream._read()
  stream._read()

  let expected = ['a', 'b', 'c']

  stream.on('data', (chunk) => {
    is(chunk, expected.shift())
  })
})
```

but this is all working fine - it seems the debouncing is still happening, even though it seems like there may be unnecessary calls going on.

I definitely observed that `._write(null)` was being called multiple times (in my previous testing). Again, that also seems like it wouldn't be an observable problem.

So perhaps this isn't a "bug" actually? Unless you can think of a way to expose incorrect behaviour through this?

It still seems worth fixing though to me, perhaps just without a test!

**Comment by mcollina** [comment]
Seems to be an optimization! I'm good with a PR with no tests on this one.
